# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ddalkkak_pb2 as ddalkkak__pb2


class DdalkkakStub(object):
    """RPC service 이름 정의(카멜케이스) => pb2_grpc에서 서비스명Servicer라는 클래스 생김
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TestFunc = channel.unary_unary(
                '/ddalkkak_package.Ddalkkak/TestFunc',
                request_serializer=ddalkkak__pb2.TestRequest.SerializeToString,
                response_deserializer=ddalkkak__pb2.TestReply.FromString,
                )


class DdalkkakServicer(object):
    """RPC service 이름 정의(카멜케이스) => pb2_grpc에서 서비스명Servicer라는 클래스 생김
    """

    def TestFunc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DdalkkakServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TestFunc': grpc.unary_unary_rpc_method_handler(
                    servicer.TestFunc,
                    request_deserializer=ddalkkak__pb2.TestRequest.FromString,
                    response_serializer=ddalkkak__pb2.TestReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ddalkkak_package.Ddalkkak', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Ddalkkak(object):
    """RPC service 이름 정의(카멜케이스) => pb2_grpc에서 서비스명Servicer라는 클래스 생김
    """

    @staticmethod
    def TestFunc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ddalkkak_package.Ddalkkak/TestFunc',
            ddalkkak__pb2.TestRequest.SerializeToString,
            ddalkkak__pb2.TestReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
