# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ddalkkak.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x64\x61lkkak.proto\x12\x10\x64\x64\x61lkkak_package\"\x1b\n\x0bTestRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\'\n\tTestReply\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t2T\n\x08\x44\x64\x61lkkak\x12H\n\x08TestFunc\x12\x1d.ddalkkak_package.TestRequest\x1a\x1b.ddalkkak_package.TestReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ddalkkak_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TESTREQUEST']._serialized_start=36
  _globals['_TESTREQUEST']._serialized_end=63
  _globals['_TESTREPLY']._serialized_start=65
  _globals['_TESTREPLY']._serialized_end=104
  _globals['_DDALKKAK']._serialized_start=106
  _globals['_DDALKKAK']._serialized_end=190
# @@protoc_insertion_point(module_scope)
