export const MainGreen: string = '#006E7F'
export const MainYellow: string = '#F8CB2E'
export const MainOrange: string = '#EE5007'
export const MainRed: string = '#B22727'
export const White: string = '#FDFFFD'
export const Black: string = '#0D0D0D'
export const Gray: string = '#C0C0C0'
export const LightGray: string = '#ECECEC'
